### ISSUE TITLE
Flathub shows version as 5.1.0 instead of 5.1.3

### ISSUE THREAD

**Issue by TheJanzap** [flathub/org.kde.kmymoney#10]
On the Flathub page of KMyMoney, it still displays the release notes of 5.1.0 instead of 5.1.3, which is the version that actually gets installed.
Opening the Flathub package in KDE Discover also displays the version as 5.1.0, released on 14.06.20

**Comment by Justinzobel** [comment]
Looks like they have failed to update the appdata which is where this information comes from. I've created the issue with KMyMoney here https://invent.kde.org/office/kmymoney/-/issues/77 to track this issue.

**Comment by TheJanzap** [comment]
Sorry for re-opening this, but while this problem seems to be fixed upstream, the actual Flathub entry still hasn't updated. I don't know how Flatpak appdata works, so is some kind of action required to refresh it?

**Comment by Justinzobel** [comment]
Not unless upstream rolls a new release of 5.1.3 which is unlikely. It will
be fixed in the next release I imagine.
